### ISSUE TITLE
ModuleNotFoundError: No module named 'pulses'

### ISSUE THREAD

**Issue by Six6stRINgs** [gtri/gr-pdw#3]
# An error occurred while running **virtual_pdw.grc**

## Screenshot
![image](https://github.com/user-attachments/assets/2e39a430-063d-4e9c-90b9-94476d7ef499)

## Info
```
Traceback (most recent call last):
  File "/home/gr-pdw/apps/virtual_pdw.py", line 29, in <module>
    from pulses import pulses  # grc-generated hier_block
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pulses'
```

## Env
- OS: Ubuntu 22.04 (WSL2)
- Python: 3.12 (Conda Environment)
- GNU Radio: 3.10.11.0

## Additional
At first, when following the  **make install** to install **gr-pdw**, it was installed in the default Python path of the system instead of my Conda environment. Therefore, I copied the files to my Conda environment path using the **cp** command based on the installed files.

Besides, when I run **gnuradio-companion**, there are also three errors:
```
pdw_pdw_to_file.block.yml                block: error: Value type 'NoneType' for 'outputs' not in valid types
pdw_usrp_power_cal_table.block.yml       block: error: Value type 'NoneType' for 'inputs' not in valid types
pdw_virtual_power_cal_table.block.yml    block: error: Value type 'NoneType' for 'inputs' not in valid types
```

**Comment by Six6stRINgs** [comment]
I installed **pulses** by command **pip install pulses**. 
- Installation Info:
```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pulses
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0b/27/30208da1cf6ba84fe0a5839fd013cbfdb9deadd944b7b95cf3d72f8af6a4/pulses-1.0.2-py3-none-any.whl (21 kB)
Collecting rpi-gpio<0.8.0,>=0.7.1 (from pulses)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c4/0f/10b524a12b3445af1c607c27b2f5ed122ef55756e29942900e5c950735f2/RPi.GPIO-0.7.1.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: rpi-gpio
  Building wheel for rpi-gpio (setup.py) ... done
  Created wheel for rpi-gpio: filename=RPi.GPIO-0.7.1-cp312-cp312-linux_x86_64.whl size=30449 sha256=d7eab9c66d131415cd970365dc34bbb35c2fd4026d04a0f07ac8981166809370
  Stored in directory: /root/.cache/pip/wheels/74/70/b9/8bf6160e418236edd217167a5b97411858feebb11df45ddaac
Successfully built rpi-gpio
Installing collected packages: rpi-gpio, pulses
Successfully installed pulses-1.0.2 rpi-gpio-0.7.1
```
There is still an error:
```
Traceback (most recent call last):
  File "/home/gr-pdw/apps/virtual_pdw.py", line 348, in <module>
    main()
  File "/home/gr-pdw/apps/virtual_pdw.py", line 325, in main
    tb = top_block_cls()
         ^^^^^^^^^^^^^^^
  File "/home/gr-pdw/apps/virtual_pdw.py", line 171, in __init__
    self.pulses_0 = pulses(
                    ^^^^^^^
TypeError: 'module' object is not callable
```

Then I checked the code of **pulses**. It seems that this **pulses** from **pip** is not the correct package for GR-PDW.

> [Project description from PyPi (pulses):](https://pypi.org/project/pulses/)
Pulses is a python module to drive LEDs on RPi using PWM (Pulse Width Modulation)

How could I get the corresponding **pulses** package for GNU Radio/GR-PDW?

**Comment by thumphries-gtri** [comment]
Hey @Six6stRINgs,

Pulses is a heir block that should have been included, my mistake. I'll get that added.

**Comment by thumphries-gtri** [comment]
Hey @Six6stRINgs ,

Apologies, this block is already included:

gr-pdw/examples/pulse_gen_heir.grc

Open that in GRC and run it to generate. Thanks for bringing it to my attention, I'll update the README.
